name: Send a Tweet
on: [push]
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: log
        run: echo "::set-env name=POST_COMMIT_MESSAGE::$(git log --no-merges -1 --pretty='%B')"; echo "::set-env name=POST_COMMIT_HASH::$(git log --no-merges -1 --pretty='%h')"
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "New checkout to https://github.com/slapelachie/kadai \n ${{ env.POST_COMMIT_HASH }}: ${{ env.POST_COMMIT_MESSAGE }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
